# Generated by Selenium IDE
from webbrowser import Chrome
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestQuerytest():
  def setup_method(self, method=None):
    self.driver = webdriver.Chrome(executable_path=r'/home/xk/IT_Capstone_Project/main/DecarbonisingWastewaterTreatment/test/geckodriver')
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_querytest(self):
    self.driver.get("file:///home/xk/IT_Capstone_Project/main/DecarbonisingWastewaterTreatment/static/data_report.html#Data-Report")
    self.driver.find_element(By.CSS_SELECTOR, "form").click()
    self.driver.find_element(By.ID, "query_id").click()
    self.driver.find_element(By.ID, "query_id").send_keys("2")
    value = self.driver.find_element(By.ID, "query_id").get_attribute("value")
    assert value == "2"
    self.driver.find_element(By.CSS_SELECTOR, ".query_download:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, "body").click()
    self.driver.close()
 
if __name__=='__main__':
    test = TestQuerytest()
    test.setup_method()
    test.test_querytest()
    time.sleep(2)
    
    test.teardown_method()
